### ISSUE TITLE
Interop with standard Html

### ISSUE THREAD

**Issue by anmolitor** [miniBill/elm-html-with-context#2]
Hi Leonardo,

I am currently switching from Elm-UI to a Tailwind based approach and thus from your Library elm-ui-with-context to this one.
Previously I had some event handlers from https://package.elm-lang.org/packages/mpizenberg/elm-pointer-events/latest/Html-Events-Extra-Pointer, which I would be able to use easily with `Element.htmlAttribute`.
I noticed during the migration that there seems to be no such escape hatch in this package.

I propose that two new functions are added (names are up to discussion):

```
fromHtml : Html.Html msg -> Html context msg
fromHtml html = Html (always html)


fromHtmlAttribute : Html.Attribute msg -> Attribute context msg
fromHtmlAttribute attribute = Attribute (always attribute)
```

What do you think? Is there an alternative I did not understand?

**Comment by miniBill** [comment]
Yeah, there are currently no escape hatches, and you're right I should add them!

I would name them `html` and `htmlAttribute` I think? :thinking: The `from*` names are not bad thought.

I currently don't have bandwidth for doing this, but I'll accept a PR

**Comment by anmolitor** [comment]
https://github.com/miniBill/elm-html-with-context/pull/3

Does this PR make sense? I haven't worked with elm-codegen before.

**Comment by miniBill** [comment]
Yes it does!

**Comment by miniBill** [comment]
Published!
